package patch

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// PatchRef is the compact, safe-to-list identity of one saved show patch.
// The default patch retains the install's historical file path; later shows
// live beside it in a catalog directory.
type PatchRef struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	EntryCount int       `json:"entryCount"`
	ModifiedAt time.Time `json:"modifiedAt"`
	Active     bool      `json:"active"`
}

const defaultPatchID = "default"

func (st *Store) initCatalogActive() {
	if st.path == "" {
		return
	}
	st.catalogDir = st.path + ".patches"
	marker := st.catalogDir + ".active"
	data, err := os.ReadFile(marker)
	if err != nil {
		return
	}
	id := strings.TrimSpace(string(data))
	if id == "" || id == defaultPatchID || !validSavedPatchID(id) {
		return
	}
	st.activePath = st.catalogPath(id)
	st.patch = nil // never silently fall back to a different show on a damaged active file
	if p, ok := loadPatchFile(st.catalogPath(id)); ok {
		st.patch = &p
		st.activePath = st.catalogPath(id)
	}
}

// Context is cheap enough for a persistent UI status strip; it never clones
// channel maps or saved baselines just to obtain the active show's name.
func (st *Store) Context() (string, bool) {
	st.mu.Lock()
	defer st.mu.Unlock()
	if st.patch == nil {
		return "", false
	}
	return st.patch.Name, true
}

func loadPatchFile(path string) (Patch, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Patch{}, false
	}
	var p Patch
	if json.Unmarshal(data, &p) != nil {
		return Patch{}, false
	}
	migrate(&p)
	return p, true
}

func (st *Store) catalogPath(id string) string {
	return filepath.Join(st.catalogDir, id+".json")
}

// validSavedPatchID accepts only IDs generated by CreatePatch. This makes
// LoadPatch's path construction safe even though its id ultimately comes
// from an HTTP path segment.
func validSavedPatchID(id string) bool {
	if !strings.HasPrefix(id, "p-") || len(id) == 2 {
		return false
	}
	for _, r := range id[2:] {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

// ListPatches returns every readable saved show. Corrupt files are never
// offered as valid patches and are left untouched for recovery.
func (st *Store) ListPatches() []PatchRef {
	st.mu.Lock()
	defer st.mu.Unlock()
	refs := make([]PatchRef, 0)
	if st.path == "" {
		if st.patch != nil {
			refs = append(refs, PatchRef{ID: defaultPatchID, Name: st.patch.Name, EntryCount: len(st.patch.Entries), ModifiedAt: st.patch.ModifiedAt, Active: true})
		}
		return refs
	}
	if p, ok := loadPatchFile(st.path); ok {
		refs = append(refs, PatchRef{ID: defaultPatchID, Name: p.Name, EntryCount: len(p.Entries), ModifiedAt: p.ModifiedAt, Active: st.activePath == st.path})
	}
	files, _ := filepath.Glob(filepath.Join(st.catalogDir, "*.json"))
	for _, file := range files {
		if p, ok := loadPatchFile(file); ok {
			id := strings.TrimSuffix(filepath.Base(file), ".json")
			refs = append(refs, PatchRef{ID: id, Name: p.Name, EntryCount: len(p.Entries), ModifiedAt: p.ModifiedAt, Active: st.activePath == file})
		}
	}
	sort.Slice(refs, func(i, j int) bool { return refs[i].ModifiedAt.After(refs[j].ModifiedAt) })
	return refs
}

// CreatePatch starts and activates a new, empty named show without touching
// any existing saved patch. It returns the active patch and its stable ID.
func (st *Store) CreatePatch(name string) (PatchRef, Patch, error) {
	st.mu.Lock()
	defer st.mu.Unlock()
	if strings.TrimSpace(name) == "" {
		return PatchRef{}, Patch{}, fmt.Errorf("patch: name is required")
	}
	now := time.Now()
	id := fmt.Sprintf("p-%d", now.UnixNano())
	if st.path == "" {
		id = defaultPatchID
	} else if err := os.MkdirAll(st.catalogDir, 0755); err != nil {
		return PatchRef{}, Patch{}, err
	}
	p := Patch{SchemaVersion: CurrentSchemaVersion, Name: strings.TrimSpace(name), CreatedAt: now, ModifiedAt: now, Entries: make([]Entry, 0)}
	path := st.activePath
	if st.path != "" {
		path = st.catalogPath(id)
	}
	if err := savePatch(path, p); err != nil {
		return PatchRef{}, Patch{}, err
	}
	if st.path != "" {
		if err := atomicWrite(st.catalogDir+".active", []byte(id)); err != nil {
			return PatchRef{}, Patch{}, err
		}
	}
	st.patch = &p
	st.activePath = path
	return PatchRef{ID: id, Name: p.Name, EntryCount: 0, ModifiedAt: p.ModifiedAt, Active: true}, clonePatch(p), nil
}

// LoadPatch switches only the active show patch. It never mutates the saved
// fixture/commit data in either the old or new patch.
func (st *Store) LoadPatch(id string) (Patch, error) {
	st.mu.Lock()
	defer st.mu.Unlock()
	if st.path == "" {
		return Patch{}, fmt.Errorf("patch: named patches require persistence")
	}
	if id != defaultPatchID && !validSavedPatchID(id) {
		return Patch{}, fmt.Errorf("patch: invalid saved patch id %q", id)
	}
	path := st.path
	if id != defaultPatchID {
		path = st.catalogPath(id)
	}
	p, ok := loadPatchFile(path)
	if !ok {
		return Patch{}, fmt.Errorf("patch: saved patch %q was not found or could not be read", id)
	}
	if err := os.MkdirAll(st.catalogDir, 0755); err != nil {
		return Patch{}, err
	}
	if err := atomicWrite(st.catalogDir+".active", []byte(id)); err != nil {
		return Patch{}, err
	}
	st.patch = &p
	st.activePath = path
	return clonePatch(p), nil
}
